TRUNCATE TABLE [Resource] 
GO
INSERT INTO [dbo].[Resource] VALUES (newid(), 'SCHOOL_MANT', 'es-CR', 'Mantenimiento Escuelas')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'SCHOOL_NAME', 'es-CR', 'Nombre Escuela')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'DESCRIPTION', 'es-CR', 'Descripción')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'SCHOOL_CODE', 'es-CR', 'Codigo Escuela')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'UPDATE', 'es-CR', 'Actualizar')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'CANCEL', 'es-CR', 'Cancelar')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'DELETE', 'es-CR', 'Eliminar')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'EDIT', 'es-CR', 'Editar')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'DELETE_CONFIRMATION', 'es-CR', '¿Está seguro que desea eliminar el registro?')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'IS_EQUAL_TO', 'es-CR', 'Sean iguales a')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'IS_NOT_EQUAL_TO', 'es-CR', 'Sean diferentes de')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'STARTS_WITH', 'es-CR', 'Empiezan con')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'CONTAINS', 'es-CR', 'Contienen')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'DOES_NOT_CONTAIN', 'es-CR', 'No Contienen')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'ENDS_WITH', 'es-CR', 'Terminan con')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'FIND', 'es-CR', 'Buscar')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'CLEAN', 'es-CR', 'Limpiar')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'FIND_VAL_WHAT', 'es-CR', 'Buscar valores que:')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'ADD_SCHOOL', 'es-CR', 'Agregar Escuela')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'NO_RECORDS', 'es-CR', 'No hay Registros')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'DISPLAY_GRID', 'es-CR', '{0} - {1} de {2} registros')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'ITEMS_PER_PAGE', 'es-CR', 'Registros por página')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'PAGE', 'es-CR', 'Página')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'OF_GRID', 'es-CR', 'de {0}')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'FIRST_PAGE', 'es-CR', 'Primera Página')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'PREVIOUS_PAGE', 'es-CR', 'Página Anterior')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'NEXT_PAGE', 'es-CR', 'Siguiente Página')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'LAST_PAGE', 'es-CR', 'Ultima Página')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'CLASSROOM_MANT', 'es-CR', 'Mantenimiento Aulas')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'CLASSROOM_CODE', 'es-CR', 'Código del Aula')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'ADD_CLASSROOM', 'es-CR', 'Agregar Aula')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'LOCATION_MANT', 'es-CR', 'Mantenimiento Lugares Físicos')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'LOCATION_LINE1', 'es-CR', 'Dirección')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'LOCATION_LINE2', 'es-CR', 'Otras Señas')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'LOCATION_NAME', 'es-CR', 'Nombre del Lugar')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'ADD_LOCATION', 'es-CR', 'Agregar Lugar Físico')
--Login View
INSERT INTO [dbo].[Resource] VALUES (newid(), 'LOGIN_TITLE', 'es-CR', 'Inicio de sesión.')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'REQUIRED', 'es-CR', '{0} es requerido')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'CURRENT_PASS', 'es-CR', 'Contraseña Actual')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'PASS_STRING_LENGTH', 'es-CR', '{0} debe tener al menos {2} caracteres.')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'NEW_PASSWORD', 'es-CR', 'Nueva Contraseña')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'OLD_PASSWORD', 'es-CR', 'Contraseña Actual')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'PASS_CONFIRM', 'es-CR', 'Confirmar Contraseña')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'PASS_CONFIRM_ERR', 'es-CR', 'Las contraseñas no coinciden.')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'USER', 'es-CR', 'Usuario')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'PASSWORD', 'es-CR', 'Contraseña')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'REMEMBER', 'es-CR', 'Recordar')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'USERNAME', 'es-CR', 'Nombre Usuario')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'EMAIL', 'es-CR', 'Correo Electrónico')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'SIGNIN', 'es-CR', 'Ingresar')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'REGISTER', 'es-CR', 'Registrar')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'NEW_USER', 'es-CR', 'Registrar un nuevo Usuario') 
INSERT INTO [dbo].[Resource] VALUES (newid(), 'PASS_STRING_LENGTH1', 'es-CR', 'La Contraseña debe tener al menos')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'PASS_STRING_LENGTH2', 'es-CR', 'caracteres.')
