TRUNCATE TABLE [Resource] 
GO
--SCHOOL VIEW 
INSERT INTO [dbo].[Resource] VALUES (newid(), 'SCHOOL_MANT', 'es-CR', 'Mantenimiento Escuelas')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'SCHOOL_NAME', 'es-CR', 'Nombre Escuela')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'DESCRIPTION', 'es-CR', 'Descripción')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'SCHOOL_CODE', 'es-CR', 'Codigo Escuela')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'ADD_SCHOOL', 'es-CR', 'Agregar Escuela')
-- KENDO Grid
INSERT INTO [dbo].[Resource] VALUES (newid(), 'UPDATE', 'es-CR', 'Actualizar')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'CANCEL', 'es-CR', 'Cancelar')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'DELETE', 'es-CR', 'Eliminar')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'EDIT', 'es-CR', 'Editar')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'DELETE_CONFIRMATION', 'es-CR', '¿Está seguro que desea eliminar el registro?')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'IS_EQUAL_TO', 'es-CR', 'Sean iguales a')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'IS_NOT_EQUAL_TO', 'es-CR', 'Sean diferentes de')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'STARTS_WITH', 'es-CR', 'Empiezan con')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'CONTAINS', 'es-CR', 'Contienen')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'DOES_NOT_CONTAIN', 'es-CR', 'No Contienen')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'ENDS_WITH', 'es-CR', 'Terminan con')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'FIND', 'es-CR', 'Buscar')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'CLEAN', 'es-CR', 'Limpiar')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'FIND_VAL_WHAT', 'es-CR', 'Buscar valores que:')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'NO_RECORDS', 'es-CR', 'No hay Registros')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'DISPLAY_GRID', 'es-CR', '{0} - {1} de {2} registros')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'ITEMS_PER_PAGE', 'es-CR', 'Registros por página')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'PAGE', 'es-CR', 'Página')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'OF_GRID', 'es-CR', 'de {0}')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'FIRST_PAGE', 'es-CR', 'Primera Página')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'PREVIOUS_PAGE', 'es-CR', 'Página Anterior')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'NEXT_PAGE', 'es-CR', 'Siguiente Página')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'LAST_PAGE', 'es-CR', 'Ultima Página')
--Classroom View
INSERT INTO [dbo].[Resource] VALUES (newid(), 'CLASSROOM_MANT', 'es-CR', 'Mantenimiento Aulas')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'CLASSROOM_CODE', 'es-CR', 'Código del Aula')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'ADD_CLASSROOM', 'es-CR', 'Agregar Aula')
--Location View
INSERT INTO [dbo].[Resource] VALUES (newid(), 'LOCATION_MANT', 'es-CR', 'Mantenimiento Lugares Físicos')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'LOCATION_LINE1', 'es-CR', 'Dirección')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'LOCATION_LINE2', 'es-CR', 'Otras Señas')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'LOCATION_NAME', 'es-CR', 'Nombre del Lugar')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'ADD_LOCATION', 'es-CR', 'Agregar Lugar Físico')
--Authentication View
INSERT INTO [dbo].[Resource] VALUES (newid(), 'LOGIN_TITLE', 'es-CR', 'Inicio de sesión.')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'REQUIRED', 'es-CR', '{0} es requerido')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'CURRENT_PASS', 'es-CR', 'Contraseña Actual')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'PASS_STRING_LENGTH', 'es-CR', '{0} debe tener al menos {2} caracteres.')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'NEW_PASSWORD', 'es-CR', 'Nueva Contraseña')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'OLD_PASSWORD', 'es-CR', 'Contraseña Actual')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'PASS_CONFIRM', 'es-CR', 'Confirmar Contraseña')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'PASS_CONFIRM_ERR', 'es-CR', 'Las contraseñas no coinciden.')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'USER', 'es-CR', 'Usuario')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'PASSWORD', 'es-CR', 'Contraseña')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'REMEMBER', 'es-CR', 'Recordar')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'USERNAME', 'es-CR', 'Nombre Usuario')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'EMAIL', 'es-CR', 'Correo Electrónico')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'SIGNIN', 'es-CR', 'Ingresar')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'REGISTER', 'es-CR', 'Registrar')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'NEW_USER', 'es-CR', 'Registrar un nuevo Usuario') 
INSERT INTO [dbo].[Resource] VALUES (newid(), 'PASS_STRING_LENGTH1', 'es-CR', 'La Contraseña debe tener al menos')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'PASS_STRING_LENGTH2', 'es-CR', 'caracteres.')
-- HOME Menu
INSERT INTO [dbo].[Resource] VALUES (newid(), 'HOME', 'es-CR', 'Inicio')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'STUDENT', 'es-CR', 'Estudiante')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'MAINTENANCE', 'es-CR', 'Mantenimiento')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'PROGRAM_PLAN_COURSE', 'es-CR', 'Programas, Planes y Cursos')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'ENROLLMENT', 'es-CR', 'Matrícula')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'NOTES_REGISTER', 'es-CR', 'Registro de Notas')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'RECORDS', 'es-CR', 'Registro de Actas')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'CERTIFICATIONS', 'es-CR', 'Certificaciones')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'AUDIT', 'es-CR', 'Auditoría')
--Maintenance Details
INSERT INTO [dbo].[Resource] VALUES (newid(), 'SCHOOL', 'es-CR', 'Escuelas')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'SCHOOL_DETAIL', 'es-CR', 'Esta opción permite listar, agregar, modificar y eliminar una escuela')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'CLASSROOM', 'es-CR', 'Aulas')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'CLASSROOM_DETAIL', 'es-CR', 'Esta opción permite listar, agregar, modificar y eliminar un aula o espacio donde se imparte ')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'LOCATION', 'es-CR', 'Lugares Físicos')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'LOCATION_DETAIL', 'es-CR', 'Esta opción permite listar, agregar, modificar y eliminar un lugar físico o geográfico')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'MODALITY_TYPE', 'es-CR', 'Tipos de Modalidad')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'MODALITY_TYPE_DETAIL', 'es-CR', 'Esta opción permite listar, agregar, modificar y eliminar los tipos de modalidades')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'REQUERIMENT', 'es-CR', 'Tipos de Requisitos')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'REQUERIMENT_DETAIL', 'es-CR', 'Esta opción permite listar, agregar, modificar y eliminar los tipos de requisitos')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'USERS', 'es-CR', 'Usuarios')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'USERS_DETAIL', 'es-CR', 'Esta opción permite listar, agregar, modificar y eliminar usuarios del sistema.')
--Student Details
INSERT INTO [dbo].[Resource] VALUES (newid(), 'COURSE_CONSULT', 'es-CR', 'Consulta de Cursos')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'COURSE_CONSULT_DETAILS', 'es-CR', 'Se muestran los cursos que un estudiante esta llevando y la información asociada al curso')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'ACADEMIC_HISTORY', 'es-CR', 'Historial Académico')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'ACADEMIC_HISTORY_DETAILS', 'es-CR', 'Esta opción permite sacar un historial de cursos y las notas respectivas del estudiante')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'SCORE_CONSULT', 'es-CR', 'Consulta de Notas')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'SCORE_CONSULT_DETAILS', 'es-CR', 'Esta opción permite ver las notas de cada curso reportadas por el profesor')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'STUDENT_DETAILS', 'es-CR', 'Esta opción permite listar, agregar, modificar y eliminar estudiantes.')
--Programs, Plans and Courses Details
INSERT INTO [dbo].[Resource] VALUES (newid(), 'PROGRAMS', 'es-CR', 'Programas')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'PROGRAMS_DETAIL', 'es-CR', 'Esta opción permite listar, agregar, modificar y eliminar un programa')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'PLAN', 'es-CR', 'Planes')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'PLAN_DETAIL', 'es-CR', 'Esta opción permite listar, agregar, modificar y eliminar un plan')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'COURSES', 'es-CR', 'Cursos')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'COURSES_DETAIL', 'es-CR', 'Esta opción permite listar, agregar, modificar y eliminar un curso')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'LINK_PLAN_COURSE', 'es-CR', 'Vincular cursos a Planes')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'LINK_PLAN_COURSE_DETAILS', 'es-CR', 'Esta opción permite listar, agregar, modificar y eliminar los cursos asociados a los planes')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'PLAN_VERSION', 'es-CR', 'Versionamiento de Planes')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'PLAN_VERSION_DETAILS', 'es-CR', 'Esta opción permite crear una versión de un plan de estudio vigente. El Sistema crea una versión copia del plan actual y en el nuevo se prodrá hacer los cambios respectivos, quedando el anterior como una versión histórica')
--Enrollment Details
INSERT INTO [dbo].[Resource] VALUES (newid(), 'ENROLLMENTS', 'es-CR', 'Matrículas')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'ENROLLMENTS_DETAIL', 'es-CR', 'Esta opción permite listar, agregar, modificar y eliminar una instancia de matrícula')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'ENROLLMENT_STUDENT', 'es-CR', 'Matrícula de Estudiantes')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'ENROLLMENT_STUDENT_DETAIL', 'es-CR', 'Esta opción permite listar, agregar, modificar y eliminar un estudiante en una matrícula')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'VAL_COURSE', 'es-CR', 'Convalidación de Cursos')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'VAL_COURSE_DETAIL', 'es-CR', 'Esta opción permite realizar la convalidación de cursos por estudiante')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'STUDENT_ENROLLMENT_CONSULT', 'es-CR', 'Consulta de Matrículas por Estudiante')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'STUDENT_ENROLLMENT_CONSULT_DETAIL', 'es-CR', 'Esta opción permite verificar si un estudiante puede matricularse en un determinado plan')
--Records Details
INSERT INTO [dbo].[Resource] VALUES (newid(), 'RECORDS_COURSE', 'es-CR', 'Registro de Actas por curso')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'RECORDS_COURSE_DETAIL', 'es-CR', 'Esta opción permite hacer el registro definitivo de las notas de los estudiantes en un determinado curso')
--NOTES Details
INSERT INTO [dbo].[Resource] VALUES (newid(), 'NOTES_COURSE_REGISTER', 'es-CR', 'Registro de Notas por Curso')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'NOTES_COURSE_REGISTER_DETAIL', 'es-CR', 'Esta opción permite agregar y modificar las notas de los estudiantes matriculados en un determinado curso')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'NOTES_IMPORT', 'es-CR', 'Importar Notas')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'NOTES_IMPORT_DETAIL', 'es-CR', 'Esta opción permite importar notas de estudiantes por curso desde un archivo en formato CSV')
--Certifications Details
INSERT INTO [dbo].[Resource] VALUES (newid(), 'TEMPLATES', 'es-CR', 'Plantillas')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'TEMPLATES_DETAIL', 'es-CR', 'Esta opción permite listar, agregar, modificar y eliminar plantillas de certificaciones')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'PRINT_CERTIFICATION', 'es-CR', 'Imprimir Certificaciones')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'PRINT_CERTIFICATION_DETAIL', 'es-CR', 'Esta opción permite realizar la impresión de las certificaciones de un plan')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'LINK_PLAN_TEMPLATE', 'es-CR', 'Vincular Plantillas por Plan')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'LINK_PLAN_TEMPLATE_DETAIL', 'es-CR', 'Esta opción permite vincular una platilla a un determiando plan de estudios')
--Auditing Details
INSERT INTO [dbo].[Resource] VALUES (newid(), 'RECORDS1', 'es-CR', 'Notas')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'AUDIT_DETAIL', 'es-CR', 'Esta opción permite listar o detallar lo referente al historial de este catálogo')
--Footer
INSERT INTO [dbo].[Resource] VALUES (newid(), 'SIGN', 'es-CR', 'B&B Development, Todos los derechos reservados')
--Modality View
INSERT INTO [dbo].[Resource] VALUES (newid(), 'MODALITY_MANT', 'es-CR', 'Mantenimiento de Modalidades')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'MODALITY', 'es-CR', 'Tipos de Modalidad')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'MODALITY_NAME', 'es-CR', 'Modalidad')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'PERIOD', 'es-CR', 'Periodo')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'ADD_MODALITY', 'es-CR', 'Agregar Modalidad')
--Course View
INSERT INTO [dbo].[Resource] VALUES (newid(), 'COURSE_MANT', 'es-CR', 'Mantenimiento de Cursos')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'COURSE_NAME', 'es-CR', 'Nombre del Curso')
INSERT INTO [dbo].[Resource] VALUES (newid(), 'ADD_COURSE', 'es-CR', 'Agregar Curso')