

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FTMatricula.Utilities.Helper
{
    public static class ModelResources
    {
        public static string ACADEMIC_HISTORY { get { return Resources.GetValue("ACADEMIC_HISTORY"); } }
        public static string ACADEMIC_HISTORY_DETAILS { get { return Resources.GetValue("ACADEMIC_HISTORY_DETAILS"); } }
        public static string ACADEMIC_INFORMATION { get { return Resources.GetValue("ACADEMIC_INFORMATION"); } }
        public static string ADD_CLASSROOM { get { return Resources.GetValue("ADD_CLASSROOM"); } }
        public static string ADD_COURSE { get { return Resources.GetValue("ADD_COURSE"); } }
        public static string ADD_LOCATION { get { return Resources.GetValue("ADD_LOCATION"); } }
        public static string ADD_MODALITY { get { return Resources.GetValue("ADD_MODALITY"); } }
        public static string ADD_PLAN { get { return Resources.GetValue("ADD_PLAN"); } }
        public static string ADD_REQ { get { return Resources.GetValue("ADD_REQ"); } }
        public static string ADD_SCHEME { get { return Resources.GetValue("ADD_SCHEME"); } }
        public static string ADD_SCHOOL { get { return Resources.GetValue("ADD_SCHOOL"); } }
        public static string ADD_STUDENT { get { return Resources.GetValue("ADD_STUDENT"); } }
        public static string ADD_STUDENT_TITLE { get { return Resources.GetValue("ADD_STUDENT_TITLE"); } }
        public static string ADD_USER { get { return Resources.GetValue("ADD_USER"); } }
        public static string ADD_USERS_TITLE { get { return Resources.GetValue("ADD_USERS_TITLE"); } }
        public static string ADDED_COURSES { get { return Resources.GetValue("ADDED_COURSES"); } }
        public static string ADITIONAL_DATA { get { return Resources.GetValue("ADITIONAL_DATA"); } }
        public static string AUDIT { get { return Resources.GetValue("AUDIT"); } }
        public static string AUDIT_DETAIL { get { return Resources.GetValue("AUDIT_DETAIL"); } }
        public static string CANCEL { get { return Resources.GetValue("CANCEL"); } }
        public static string CERTIFICATIONS { get { return Resources.GetValue("CERTIFICATIONS"); } }
        public static string CLASSROOM { get { return Resources.GetValue("CLASSROOM"); } }
        public static string CLASSROOM_CODE { get { return Resources.GetValue("CLASSROOM_CODE"); } }
        public static string CLASSROOM_DETAIL { get { return Resources.GetValue("CLASSROOM_DETAIL"); } }
        public static string CLASSROOM_MANT { get { return Resources.GetValue("CLASSROOM_MANT"); } }
        public static string CLEAN { get { return Resources.GetValue("CLEAN"); } }
        public static string CONTAINS { get { return Resources.GetValue("CONTAINS"); } }
        public static string COORDINATOR { get { return Resources.GetValue("COORDINATOR"); } }
        public static string COUNTRY { get { return Resources.GetValue("COUNTRY"); } }
        public static string COURSE_CODE { get { return Resources.GetValue("COURSE_CODE"); } }
        public static string COURSE_CONSULT { get { return Resources.GetValue("COURSE_CONSULT"); } }
        public static string COURSE_CONSULT_DETAILS { get { return Resources.GetValue("COURSE_CONSULT_DETAILS"); } }
        public static string COURSE_COST { get { return Resources.GetValue("COURSE_COST"); } }
        public static string COURSE_MANT { get { return Resources.GetValue("COURSE_MANT"); } }
        public static string COURSE_NAME { get { return Resources.GetValue("COURSE_NAME"); } }
        public static string COURSES { get { return Resources.GetValue("COURSES"); } }
        public static string COURSES_DETAIL { get { return Resources.GetValue("COURSES_DETAIL"); } }
        public static string CURRENT_PASS { get { return Resources.GetValue("CURRENT_PASS"); } }
        public static string DATE_OF_BIRTH { get { return Resources.GetValue("DATE_OF_BIRTH"); } }
        public static string DELETE { get { return Resources.GetValue("DELETE"); } }
        public static string DELETE_CONFIRMATION { get { return Resources.GetValue("DELETE_CONFIRMATION"); } }
        public static string DESCRIPTION { get { return Resources.GetValue("DESCRIPTION"); } }
        public static string DISPLAY_GRID { get { return Resources.GetValue("DISPLAY_GRID"); } }
        public static string DOES_NOT_CONTAIN { get { return Resources.GetValue("DOES_NOT_CONTAIN"); } }
        public static string EDIT { get { return Resources.GetValue("EDIT"); } }
        public static string EDIT_PLAN { get { return Resources.GetValue("EDIT_PLAN"); } }
        public static string EDIT_REQ { get { return Resources.GetValue("EDIT_REQ"); } }
        public static string EDIT_STUDENT_TITLE { get { return Resources.GetValue("EDIT_STUDENT_TITLE"); } }
        public static string EDIT_USERS_TITLE { get { return Resources.GetValue("EDIT_USERS_TITLE"); } }
        public static string EMAIL { get { return Resources.GetValue("EMAIL"); } }
        public static string ENDS_WITH { get { return Resources.GetValue("ENDS_WITH"); } }
        public static string ENROLLMENT { get { return Resources.GetValue("ENROLLMENT"); } }
        public static string ENROLLMENT_ADD { get { return Resources.GetValue("ENROLLMENT_ADD"); } }
        public static string ENROLLMENT_ADD_TITLE { get { return Resources.GetValue("ENROLLMENT_ADD_TITLE"); } }
        public static string ENROLLMENT_COURSES_DETAILS { get { return Resources.GetValue("ENROLLMENT_COURSES_DETAILS"); } }
        public static string ENROLLMENT_DATES { get { return Resources.GetValue("ENROLLMENT_DATES"); } }
        public static string ENROLLMENT_DESCRIPTION { get { return Resources.GetValue("ENROLLMENT_DESCRIPTION"); } }
        public static string ENROLLMENT_EXRTRA_DATES { get { return Resources.GetValue("ENROLLMENT_EXRTRA_DATES"); } }
        public static string ENROLLMENT_FECHA_BEGIN { get { return Resources.GetValue("ENROLLMENT_FECHA_BEGIN"); } }
        public static string ENROLLMENT_FECHA_END { get { return Resources.GetValue("ENROLLMENT_FECHA_END"); } }
        public static string ENROLLMENT_GENERAL_INFO { get { return Resources.GetValue("ENROLLMENT_GENERAL_INFO"); } }
        public static string ENROLLMENT_GROUPS_DETAILS { get { return Resources.GetValue("ENROLLMENT_GROUPS_DETAILS"); } }
        public static string ENROLLMENT_LOCATION { get { return Resources.GetValue("ENROLLMENT_LOCATION"); } }
        public static string ENROLLMENT_MANT { get { return Resources.GetValue("ENROLLMENT_MANT"); } }
        public static string ENROLLMENT_PLAN { get { return Resources.GetValue("ENROLLMENT_PLAN"); } }
        public static string ENROLLMENT_STUDENT { get { return Resources.GetValue("ENROLLMENT_STUDENT"); } }
        public static string ENROLLMENT_STUDENT_DETAIL { get { return Resources.GetValue("ENROLLMENT_STUDENT_DETAIL"); } }
        public static string ENROLLMENT_VERIFY_DATES { get { return Resources.GetValue("ENROLLMENT_VERIFY_DATES"); } }
        public static string ENROLLMENTS { get { return Resources.GetValue("ENROLLMENTS"); } }
        public static string ENROLLMENTS_DETAIL { get { return Resources.GetValue("ENROLLMENTS_DETAIL"); } }
        public static string FIND { get { return Resources.GetValue("FIND"); } }
        public static string FIND_VAL_WHAT { get { return Resources.GetValue("FIND_VAL_WHAT"); } }
        public static string FIRST_NAME { get { return Resources.GetValue("FIRST_NAME"); } }
        public static string FIRST_PAGE { get { return Resources.GetValue("FIRST_PAGE"); } }
        public static string GENDER { get { return Resources.GetValue("GENDER"); } }
        public static string GENDER_FEMALE { get { return Resources.GetValue("GENDER_FEMALE"); } }
        public static string GENDER_MALE { get { return Resources.GetValue("GENDER_MALE"); } }
        public static string HOME { get { return Resources.GetValue("HOME"); } }
        public static string IDENTIFICATION { get { return Resources.GetValue("IDENTIFICATION"); } }
        public static string IDENTIFICATION_TYPE { get { return Resources.GetValue("IDENTIFICATION_TYPE"); } }
        public static string IS_EQUAL_TO { get { return Resources.GetValue("IS_EQUAL_TO"); } }
        public static string IS_NOT_EQUAL_TO { get { return Resources.GetValue("IS_NOT_EQUAL_TO"); } }
        public static string ITEMS_PER_PAGE { get { return Resources.GetValue("ITEMS_PER_PAGE"); } }
        public static string KAU_INTERNET { get { return Resources.GetValue("KAU_INTERNET"); } }
        public static string KAU_NEWS { get { return Resources.GetValue("KAU_NEWS"); } }
        public static string KAU_OTHER { get { return Resources.GetValue("KAU_OTHER"); } }
        public static string KAU_TV { get { return Resources.GetValue("KAU_TV"); } }
        public static string LAST_NAME { get { return Resources.GetValue("LAST_NAME"); } }
        public static string LAST_PAGE { get { return Resources.GetValue("LAST_PAGE"); } }
        public static string LINK_PLAN_COURSE { get { return Resources.GetValue("LINK_PLAN_COURSE"); } }
        public static string LINK_PLAN_COURSE_DETAILS { get { return Resources.GetValue("LINK_PLAN_COURSE_DETAILS"); } }
        public static string LINK_PLAN_TEMPLATE { get { return Resources.GetValue("LINK_PLAN_TEMPLATE"); } }
        public static string LINK_PLAN_TEMPLATE_DETAIL { get { return Resources.GetValue("LINK_PLAN_TEMPLATE_DETAIL"); } }
        public static string LOCATION { get { return Resources.GetValue("LOCATION"); } }
        public static string LOCATION_DETAIL { get { return Resources.GetValue("LOCATION_DETAIL"); } }
        public static string LOCATION_LINE1 { get { return Resources.GetValue("LOCATION_LINE1"); } }
        public static string LOCATION_LINE2 { get { return Resources.GetValue("LOCATION_LINE2"); } }
        public static string LOCATION_MANT { get { return Resources.GetValue("LOCATION_MANT"); } }
        public static string LOCATION_NAME { get { return Resources.GetValue("LOCATION_NAME"); } }
        public static string LOGIN_TITLE { get { return Resources.GetValue("LOGIN_TITLE"); } }
        public static string MAINTENANCE { get { return Resources.GetValue("MAINTENANCE"); } }
        public static string MARITAL_STATUS { get { return Resources.GetValue("MARITAL_STATUS"); } }
        public static string MARITAL_STATUS_COHABIT { get { return Resources.GetValue("MARITAL_STATUS_COHABIT"); } }
        public static string MARITAL_STATUS_DIVORCED { get { return Resources.GetValue("MARITAL_STATUS_DIVORCED"); } }
        public static string MARITAL_STATUS_MARRIED { get { return Resources.GetValue("MARITAL_STATUS_MARRIED"); } }
        public static string MARITAL_STATUS_SINGLE { get { return Resources.GetValue("MARITAL_STATUS_SINGLE"); } }
        public static string MARITAL_STATUS_WIDOW { get { return Resources.GetValue("MARITAL_STATUS_WIDOW"); } }
        public static string MAX_LENGTH { get { return Resources.GetValue("MAX_LENGTH"); } }
        public static string MODALITY { get { return Resources.GetValue("MODALITY"); } }
        public static string MODALITY_MANT { get { return Resources.GetValue("MODALITY_MANT"); } }
        public static string MODALITY_NAME { get { return Resources.GetValue("MODALITY_NAME"); } }
        public static string MODALITY_TYPE { get { return Resources.GetValue("MODALITY_TYPE"); } }
        public static string MODALITY_TYPE_DETAIL { get { return Resources.GetValue("MODALITY_TYPE_DETAIL"); } }
        public static string NATIONAL_ID { get { return Resources.GetValue("NATIONAL_ID"); } }
        public static string NEW_PASSWORD { get { return Resources.GetValue("NEW_PASSWORD"); } }
        public static string NEW_USER { get { return Resources.GetValue("NEW_USER"); } }
        public static string NEXT_PAGE { get { return Resources.GetValue("NEXT_PAGE"); } }
        public static string NO_RECORDS { get { return Resources.GetValue("NO_RECORDS"); } }
        public static string NOTES_COURSE_REGISTER { get { return Resources.GetValue("NOTES_COURSE_REGISTER"); } }
        public static string NOTES_COURSE_REGISTER_DETAIL { get { return Resources.GetValue("NOTES_COURSE_REGISTER_DETAIL"); } }
        public static string NOTES_IMPORT { get { return Resources.GetValue("NOTES_IMPORT"); } }
        public static string NOTES_IMPORT_DETAIL { get { return Resources.GetValue("NOTES_IMPORT_DETAIL"); } }
        public static string NOTES_REGISTER { get { return Resources.GetValue("NOTES_REGISTER"); } }
        public static string OF_GRID { get { return Resources.GetValue("OF_GRID"); } }
        public static string OLD_PASSWORD { get { return Resources.GetValue("OLD_PASSWORD"); } }
        public static string OWNER { get { return Resources.GetValue("OWNER"); } }
        public static string PAGE { get { return Resources.GetValue("PAGE"); } }
        public static string PASS_CONFIRM { get { return Resources.GetValue("PASS_CONFIRM"); } }
        public static string PASS_CONFIRM_ERR { get { return Resources.GetValue("PASS_CONFIRM_ERR"); } }
        public static string PASS_STRING_LENGTH { get { return Resources.GetValue("PASS_STRING_LENGTH"); } }
        public static string PASS_STRING_LENGTH1 { get { return Resources.GetValue("PASS_STRING_LENGTH1"); } }
        public static string PASS_STRING_LENGTH2 { get { return Resources.GetValue("PASS_STRING_LENGTH2"); } }
        public static string PASSPORT_ID { get { return Resources.GetValue("PASSPORT_ID"); } }
        public static string PASSWORD { get { return Resources.GetValue("PASSWORD"); } }
        public static string PERIOD { get { return Resources.GetValue("PERIOD"); } }
        public static string PERSONAL_DATA { get { return Resources.GetValue("PERSONAL_DATA"); } }
        public static string PHONE_HOME { get { return Resources.GetValue("PHONE_HOME"); } }
        public static string PHONE_MOB { get { return Resources.GetValue("PHONE_MOB"); } }
        public static string PHONE_OFFICE { get { return Resources.GetValue("PHONE_OFFICE"); } }
        public static string PLAN { get { return Resources.GetValue("PLAN"); } }
        public static string PLAN_DETAIL { get { return Resources.GetValue("PLAN_DETAIL"); } }
        public static string PLAN_NAME { get { return Resources.GetValue("PLAN_NAME"); } }
        public static string PLAN_VERSION { get { return Resources.GetValue("PLAN_VERSION"); } }
        public static string PLAN_VERSION_DETAILS { get { return Resources.GetValue("PLAN_VERSION_DETAILS"); } }
        public static string PREVIOUS_PAGE { get { return Resources.GetValue("PREVIOUS_PAGE"); } }
        public static string PRINT_CERTIFICATION { get { return Resources.GetValue("PRINT_CERTIFICATION"); } }
        public static string PRINT_CERTIFICATION_DETAIL { get { return Resources.GetValue("PRINT_CERTIFICATION_DETAIL"); } }
        public static string PROGRAM_PLAN_COURSE { get { return Resources.GetValue("PROGRAM_PLAN_COURSE"); } }
        public static string PROGRAMS { get { return Resources.GetValue("PROGRAMS"); } }
        public static string PROGRAMS_DETAIL { get { return Resources.GetValue("PROGRAMS_DETAIL"); } }
        public static string RECORDS { get { return Resources.GetValue("RECORDS"); } }
        public static string RECORDS_COURSE { get { return Resources.GetValue("RECORDS_COURSE"); } }
        public static string RECORDS_COURSE_DETAIL { get { return Resources.GetValue("RECORDS_COURSE_DETAIL"); } }
        public static string RECORDS1 { get { return Resources.GetValue("RECORDS1"); } }
        public static string REGISTER { get { return Resources.GetValue("REGISTER"); } }
        public static string REMEMBER { get { return Resources.GetValue("REMEMBER"); } }
        public static string REQ { get { return Resources.GetValue("REQ"); } }
        public static string REQ_COURSE { get { return Resources.GetValue("REQ_COURSE"); } }
        public static string REQ_NAME { get { return Resources.GetValue("REQ_NAME"); } }
        public static string REQ_PLAN { get { return Resources.GetValue("REQ_PLAN"); } }
        public static string REQ_PROGRAM { get { return Resources.GetValue("REQ_PROGRAM"); } }
        public static string REQUERIMENT { get { return Resources.GetValue("REQUERIMENT"); } }
        public static string REQUERIMENT_DETAIL { get { return Resources.GetValue("REQUERIMENT_DETAIL"); } }
        public static string REQUIRED { get { return Resources.GetValue("REQUIRED"); } }
        public static string RESIDENT_ID { get { return Resources.GetValue("RESIDENT_ID"); } }
        public static string ROLE { get { return Resources.GetValue("ROLE"); } }
        public static string ROLE_ADMINISTRATOR { get { return Resources.GetValue("ROLE_ADMINISTRATOR"); } }
        public static string ROLE_AUDITOR { get { return Resources.GetValue("ROLE_AUDITOR"); } }
        public static string ROLE_COORDINATOR { get { return Resources.GetValue("ROLE_COORDINATOR"); } }
        public static string ROLE_SCHOOL_ADMIN { get { return Resources.GetValue("ROLE_SCHOOL_ADMIN"); } }
        public static string ROLE_STUDENT { get { return Resources.GetValue("ROLE_STUDENT"); } }
        public static string ROLE_TEACHER { get { return Resources.GetValue("ROLE_TEACHER"); } }
        public static string SAVE { get { return Resources.GetValue("SAVE"); } }
        public static string SCHEME_MANT { get { return Resources.GetValue("SCHEME_MANT"); } }
        public static string SCHEME_NAME { get { return Resources.GetValue("SCHEME_NAME"); } }
        public static string SCHOOL { get { return Resources.GetValue("SCHOOL"); } }
        public static string SCHOOL_CODE { get { return Resources.GetValue("SCHOOL_CODE"); } }
        public static string SCHOOL_DETAIL { get { return Resources.GetValue("SCHOOL_DETAIL"); } }
        public static string SCHOOL_MANT { get { return Resources.GetValue("SCHOOL_MANT"); } }
        public static string SCHOOL_NAME { get { return Resources.GetValue("SCHOOL_NAME"); } }
        public static string SCORE_CONSULT { get { return Resources.GetValue("SCORE_CONSULT"); } }
        public static string SCORE_CONSULT_DETAILS { get { return Resources.GetValue("SCORE_CONSULT_DETAILS"); } }
        public static string SIGN { get { return Resources.GetValue("SIGN"); } }
        public static string SIGNIN { get { return Resources.GetValue("SIGNIN"); } }
        public static string STARTS_WITH { get { return Resources.GetValue("STARTS_WITH"); } }
        public static string STUDENT { get { return Resources.GetValue("STUDENT"); } }
        public static string STUDENT_ADDITIONAL_ADDRESS { get { return Resources.GetValue("STUDENT_ADDITIONAL_ADDRESS"); } }
        public static string STUDENT_DETAILS { get { return Resources.GetValue("STUDENT_DETAILS"); } }
        public static string STUDENT_ENROLLMENT_CONSULT { get { return Resources.GetValue("STUDENT_ENROLLMENT_CONSULT"); } }
        public static string STUDENT_ENROLLMENT_CONSULT_DETAIL { get { return Resources.GetValue("STUDENT_ENROLLMENT_CONSULT_DETAIL"); } }
        public static string STUDENT_HOW_YOU_KNOW_ABOUT_US { get { return Resources.GetValue("STUDENT_HOW_YOU_KNOW_ABOUT_US"); } }
        public static string STUDENT_JOB_TITLE { get { return Resources.GetValue("STUDENT_JOB_TITLE"); } }
        public static string STUDENT_MAINTENANCE { get { return Resources.GetValue("STUDENT_MAINTENANCE"); } }
        public static string STUDENT_OCUPATION { get { return Resources.GetValue("STUDENT_OCUPATION"); } }
        public static string STUDENT_PHYSICA_LADDRESS { get { return Resources.GetValue("STUDENT_PHYSICA_LADDRESS"); } }
        public static string STUDENT_RECEIVE_NEWS { get { return Resources.GetValue("STUDENT_RECEIVE_NEWS"); } }
        public static string STUDENT_RECEIVE_OFFERS { get { return Resources.GetValue("STUDENT_RECEIVE_OFFERS"); } }
        public static string STUDENT_STUDIES { get { return Resources.GetValue("STUDENT_STUDIES"); } }
        public static string STUDENT_WHO_PAYS_YOUR_STUDIES { get { return Resources.GetValue("STUDENT_WHO_PAYS_YOUR_STUDIES"); } }
        public static string STUDENT_WORK_PLACE { get { return Resources.GetValue("STUDENT_WORK_PLACE"); } }
        public static string STUDENT_WORKS { get { return Resources.GetValue("STUDENT_WORKS"); } }
        public static string TEACHING_HOURS { get { return Resources.GetValue("TEACHING_HOURS"); } }
        public static string TEMPLATES { get { return Resources.GetValue("TEMPLATES"); } }
        public static string TEMPLATES_DETAIL { get { return Resources.GetValue("TEMPLATES_DETAIL"); } }
        public static string TYPE_AUTO_FILTER { get { return Resources.GetValue("TYPE_AUTO_FILTER"); } }
        public static string TYPE_NAME { get { return Resources.GetValue("TYPE_NAME"); } }
        public static string UNASSIGNED_COURSE { get { return Resources.GetValue("UNASSIGNED_COURSE"); } }
        public static string UPDATE { get { return Resources.GetValue("UPDATE"); } }
        public static string USER { get { return Resources.GetValue("USER"); } }
        public static string USER_MAINTENANCE { get { return Resources.GetValue("USER_MAINTENANCE"); } }
        public static string USERNAME { get { return Resources.GetValue("USERNAME"); } }
        public static string USERS { get { return Resources.GetValue("USERS"); } }
        public static string USERS_DETAIL { get { return Resources.GetValue("USERS_DETAIL"); } }
        public static string VAL_COURSE { get { return Resources.GetValue("VAL_COURSE"); } }
        public static string VAL_COURSE_DETAIL { get { return Resources.GetValue("VAL_COURSE_DETAIL"); } }
        public static string VERSION { get { return Resources.GetValue("VERSION"); } }
        public static string VIEW_DETAILS { get { return Resources.GetValue("VIEW_DETAILS"); } }
        public static string WPS_DADS { get { return Resources.GetValue("WPS_DADS"); } }
        public static string WPS_FAMILY { get { return Resources.GetValue("WPS_FAMILY"); } }
        public static string WPS_FUNDED { get { return Resources.GetValue("WPS_FUNDED"); } }
        public static string WPS_INSTITUTION { get { return Resources.GetValue("WPS_INSTITUTION"); } }
        public static string WPS_OTHER { get { return Resources.GetValue("WPS_OTHER"); } }
        public static string WPS_OWN_INCOME { get { return Resources.GetValue("WPS_OWN_INCOME"); } }
        public static string WPS_SCHOLARSHIP { get { return Resources.GetValue("WPS_SCHOLARSHIP"); } }


    }
}
