//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTMatricula.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationUser
    {
        public System.Guid? UserId { get; set; }
        public System.Guid? StudentID { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public Nullable<System.Guid> CountryID { get; set; }
        public string CountryName { get; set; }
        public System.Guid? MaritalStatusTypeID { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Phone3 { get; set; }
        public string RoleName { get; set; }
        public System.Guid? IdentificationTypeID { get; set; }
    }
}
