//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTMatricula.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrollmentGroup
    {
        public EnrollmentGroup()
        {
            this.EnrollmentGroupSchedules = new HashSet<EnrollmentGroupSchedule>();
            this.Scores = new HashSet<Score>();
        }
    
        public System.Guid? EnrollmentGroupID { get; set; }
        public System.Guid? EnrollmentCourseID { get; set; }
        public string GroupName { get; set; }
        public Nullable<System.Guid> ProfessorID { get; set; }
        public int Quota { get; set; }
        public Nullable<int> ExtraQuota { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<System.Guid> InsertUserID { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<System.Guid> ModifyUserID { get; set; }
        public string IpAddress { get; set; }
    
        public virtual EnrollmentCourse EnrollmentCourse { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<EnrollmentGroupSchedule> EnrollmentGroupSchedules { get; set; }
        public virtual ICollection<Score> Scores { get; set; }
    }
}
