//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTMatricula.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrollmentCourse
    {
        public EnrollmentCourse()
        {
            this.EnrollmentGroups = new HashSet<EnrollmentGroup>();
        }
    
        public System.Guid? EnrollmentCourseID { get; set; }
        public System.Guid? EnrollmentID { get; set; }
        public System.Guid? CourseID { get; set; }
        public bool IsChecked { get; set; }
        public bool HasGroups { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<System.Guid> InsertUserID { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<System.Guid> ModifyUserID { get; set; }
        public string IpAddress { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Enrollment Enrollment { get; set; }
        public virtual ICollection<EnrollmentGroup> EnrollmentGroups { get; set; }
    }
}
