//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTMatricula.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public Enrollment()
        {
            this.EnrollmentCourses = new HashSet<EnrollmentCourse>();
            this.EnrollmentStudents = new HashSet<EnrollmentStudent>();
        }
    
        public System.Guid? EnrollmentID { get; set; }
        public string Description { get; set; }
        public System.Guid? PlanID { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<System.Guid> InsertUserID { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<System.Guid> ModifyUserID { get; set; }
        public string IpAddress { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> ExtraStartDate { get; set; }
        public Nullable<System.DateTime> ExtraEndDate { get; set; }
        public System.Guid? LocationID { get; set; }
        public bool VerifyDates { get; set; }
    
        public virtual Plan Plan { get; set; }
        public virtual Location Location { get; set; }
        public virtual ICollection<EnrollmentCourse> EnrollmentCourses { get; set; }
        public virtual ICollection<EnrollmentStudent> EnrollmentStudents { get; set; }
    }
}
