//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTMatricula.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        public Plan()
        {
            this.Enrollments = new HashSet<Enrollment>();
            this.Plan_Course = new HashSet<Plan_Course>();
            this.Scheme_Plan = new HashSet<Scheme_Plan>();
        }
    
        public System.Guid? PlanID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.Guid? LocationID { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<System.Guid> InsertUserID { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<System.Guid> ModifyUserID { get; set; }
        public string IpAddress { get; set; }
    
        public virtual ICollection<Enrollment> Enrollments { get; set; }
        public virtual Location Location { get; set; }
        public virtual ICollection<Plan_Course> Plan_Course { get; set; }
        public virtual ICollection<Scheme_Plan> Scheme_Plan { get; set; }
    }
}
