//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTMatricula.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanDetail
    {
        public System.Guid? SchemeID { get; set; }
        public string SchemeName { get; set; }
        public System.Guid? PlanID { get; set; }
        public string PlanName { get; set; }
        public string Version { get; set; }
        public string Description { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
