//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTMatricula.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement
    {
        public Requirement()
        {
            this.Courses = new HashSet<Course>();
            this.Scheme_Requirement = new HashSet<Scheme_Requirement>();
        }
    
        public System.Guid RequirementID { get; set; }
        public string Name { get; set; }
        public System.Guid TypeID { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<System.Guid> InsertUserID { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<System.Guid> ModifyUserID { get; set; }
        public string IpAddress { get; set; }
    
        public virtual ICollection<Course> Courses { get; set; }
        public virtual ICollection<Scheme_Requirement> Scheme_Requirement { get; set; }
    }
}
