//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTMatricula.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public System.Guid ResourceID { get; set; }
        public string ResourceKey { get; set; }
        public string Culture { get; set; }
        public string ResourceValue { get; set; }
    }
}
