//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTMatricula.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchemeDetail
    {
        public System.Guid? SchemeID { get; set; }
        public string SchemeName { get; set; }
        public string Description { get; set; }
        public System.Guid? OwnerUserId { get; set; }
        public string OwnerName { get; set; }
        public System.Guid? CoordinatorUserId { get; set; }
        public string CoordinatorName { get; set; }
        public System.Guid? ModalityID { get; set; }
        public string ModalityName { get; set; }
    }
}
