//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTMatricula.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public School()
        {
            this.Courses = new HashSet<Course>();
            this.Schemes = new HashSet<Scheme>();
        }
    
        public System.Guid? SchoolID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<System.Guid> InsertUserID { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<System.Guid> ModifyUserID { get; set; }
        public string IpAddress { get; set; }
        public string Code { get; set; }
        public Nullable<System.Guid> AdminUserID { get; set; }
    
        public virtual ICollection<Course> Courses { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Scheme> Schemes { get; set; }
    }
}
