//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTMatricula.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class School
    {
        public School()
        {
            this.School_Scheme = new HashSet<School_Scheme>();
        }

        [ScaffoldColumn(false)]
        public System.Guid SchoolID { get; set; }
        
        public string Name { get; set; }
        public string Description { get; set; }

        [ScaffoldColumn(false)]
        public Nullable<System.DateTime> InsertDate { get; set; }
        [ScaffoldColumn(false)]
        public Nullable<System.Guid> InsertUserID { get; set; }
        [ScaffoldColumn(false)]
        public Nullable<System.DateTime> ModifyDate { get; set; }
        [ScaffoldColumn(false)]
        public Nullable<System.Guid> ModifyUserID { get; set; }
        [ScaffoldColumn(false)]
        public string IpAddress { get; set; }
        
        public string Code { get; set; }
    
        public virtual ICollection<School_Scheme> School_Scheme { get; set; }
    }
}
