//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTMatricula.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoreCriteria
    {
        public ScoreCriteria()
        {
            this.Courses = new HashSet<Course>();
        }
    
        public System.Guid? ScoreCriteriaID { get; set; }
        public Nullable<System.Guid> TypeID { get; set; }
        public string MinimumScore { get; set; }
    
        public virtual Type Type { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
    }
}
