//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTMatricula.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAdditionalData
    {
        public System.Guid? StudentID { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<System.Guid> InsertUserID { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<System.Guid> ModifyUserID { get; set; }
        public string IpAddress { get; set; }
        public string PhysicalAddress { get; set; }
        public string AdditionalAddress { get; set; }
        public string JobTitle { get; set; }
        public string WorkPlace { get; set; }
        public bool Works { get; set; }
        public bool Studies { get; set; }
        public Nullable<System.Guid> WhoPaysYourStudiesTypeID { get; set; }
        public Nullable<System.Guid> HowYouKnowAboutUsTypeID { get; set; }
        public bool ReceiveOffers { get; set; }
        public bool ReceiveNews { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Type Type { get; set; }
        public virtual Type Type1 { get; set; }
    }
}
