//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTMatricula.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Student_Course = new HashSet<Student_Course>();
            this.StudiesInformations = new HashSet<StudiesInformation>();
            this.StudentPlans = new HashSet<StudentPlan>();
        }
    
        public System.Guid? StudentID { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<System.Guid> InsertUserID { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<System.Guid> ModifyUserID { get; set; }
        public string IpAddress { get; set; }
        public System.Guid? UserID { get; set; }
        public System.Guid? IdentificationTypeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.Guid> CountryID { get; set; }
        public System.Guid? MaritalStatusTypeID { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Phone3 { get; set; }
        public Nullable<bool> IsAppUser { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Type Type { get; set; }
        public virtual Type Type1 { get; set; }
        public virtual User User { get; set; }
        public virtual StudentAdditionalData StudentAdditionalData { get; set; }
        public virtual ICollection<Student_Course> Student_Course { get; set; }
        public virtual ICollection<StudiesInformation> StudiesInformations { get; set; }
        public virtual ICollection<StudentPlan> StudentPlans { get; set; }
    }
}
