//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTMatricula.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Students = new HashSet<Student>();
            this.EnrollmentGroups = new HashSet<EnrollmentGroup>();
        }
    
        public System.Guid? ApplicationId { get; set; }
        public System.Guid? UserId { get; set; }
        public string UserName { get; set; }
        public bool IsAnonymous { get; set; }
        public System.DateTime LastActivityDate { get; set; }
    
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<EnrollmentGroup> EnrollmentGroups { get; set; }
        public virtual utbMembership Membership { get; set; }
    }
}
